### ISSUE TITLE
about swift 4

### ISSUE THREAD

**Issue by tentenlee100** [felipeflorencio/BCryptSwift#1]
Do you have any update to swift 4?

**Comment by felipeflorencio** [comment]
Hey man I did not planed anything but, it's time to update for sure, I will update until this weekend :)

**Comment by felipeflorencio** [comment]
Updated for swift 4, now I just set as version tag now for 1.0 as no one had open any issue about. So if want use last will need set tag and now the last one is Swift 4, please if not working properly or anything like please open new issue
