### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by clementleys** [felipeflorencio/BCryptSwift#4]
I am coding a macOS app. Your pod does not allow to deploy for macOS but I downloaded it to make it work on my macOS project.

Before, I was using a bcrypt c lib but, because of a memory leak, I tried you swift lib. Sadly, the c version is instantaneous while your swift version takes few seconds to execute `hashPassword()`
Do you have any idea to fix that ?

Thank you.

**Comment by felipeflorencio** [comment]
Yeap, this is a "issue" that I know, but unfortunately the time that  I made this migration is a issue about how swift handle the "problem" and yes, it's very slow if comparing with a C version, but I will check if now with last updates we are able to upgrade the performance.

**Comment by matheusalano** [comment]
Hey @felipeflorencio, do you have any news about the performance? I'm using your project, but it's taking about a minute to encrypt a password. Don't know if it helps, but I tracked the source of this bad performance and, apparently, it's here:
```
for _ in 0..<rounds{
       self.key(password)
        self.key(salt)
}
```
It's iterating 4095 times.

Thank you
